### ISSUE TITLE
Events database file for Alder Lake 

### ISSUE THREAD

**Issue by jimmylikes** [morganstanley/Xpedite#165]
Hi experts,

I'm trying to tuning the Core i9 12th cpu today and found current xpedite doesn't provide the event database yet, is it possible to support it?

here is the error I got when tunning:
"failed to locate events database file for cpu GenuineIntel-6-97-2. please consult xpedite devs to add support for this architecture"

**Comment by Mani-D** [comment]
Thanks for the details. Will make a patch to get Alder lake counters.
